In [0]:
import numpy as np

# **Numpy**

---



In [28]:
np.array([1, 2, 3, 7, 9, 10]) # Array de numpy

array([ 1,  2,  3,  7,  9, 10])

In [29]:
a = np.array([10, 30, 20, 4, 30, 51, 7, 2, 4, 40, 100])

# Slicing con arreglos de numpy
print(a[4])
print(a[3:])
print(a[3:7])
print(a[1::4])

30
[  4  30  51   7   2   4  40 100]
[ 4 30 51  7]
[30 51 40]


In [30]:
np.zeros((3, 4)) # Arreglos solo con ceros de la forma especificada (en una tupla)

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [31]:
np.ones((4, 3)) # Arreglos solo con unos de la forma especificada (en una tupla)

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [32]:
type(np.ones(3)) # Tipo del arreglo

numpy.ndarray

In [33]:
type(np.zeros(4)[3]) # Tipo de un elemento especifico del arreglo de numpy

numpy.float64

In [34]:
np.linspace(-10, 10, 21) # Array con rango de -10, 10, 21 elementos en el array

array([-10.,  -9.,  -8.,  -7.,  -6.,  -5.,  -4.,  -3.,  -2.,  -1.,   0.,
         1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.])

In [35]:
b = np.array([['x', 'y', 'z'], ['a', 'b', 'c']]) # Arreglos multidimensionales
print(b)

[['x' 'y' 'z']
 ['a' 'b' 'c']]


In [36]:
b.ndim # Numero de dimensiones del arreglo

2

In [37]:
c = [10, 7, 8, 3, 2]
np.sort(c) # Ordenacion de un arreglo

array([ 2,  3,  7,  8, 10])

In [57]:
cabeceras = [('nombre', 'S10'), ('edad', int)] # Nombres de las columnas y tipos
datos = [('AJuan', 42), ('CPedro', 21), ('BRoberto', 10)] # Datos
usuarios = np.array(datos, dtype=cabeceras) # Array con los datos y tipos

np.sort(usuarios, order='edad') # Ordenacion segun la columna edad

array([(b'BRoberto', 10), (b'CPedro', 21), (b'AJuan', 42)],
      dtype=[('nombre', 'S10'), ('edad', '<i8')])

In [59]:
np.arange(5, 10, 2) # Array en el rango de 5 a 10 con pasos de 2 en 2

array([5, 7, 9])

In [64]:
np.full((3, 4, 2), 10) # Array con la forma (3, 4, 2) lleno de solamente 10

array([[[10, 10],
        [10, 10],
        [10, 10],
        [10, 10]],

       [[10, 10],
        [10, 10],
        [10, 10],
        [10, 10]],

       [[10, 10],
        [10, 10],
        [10, 10],
        [10, 10]]])

In [68]:
np.diag([1, 2, 3, 4]) # Matriz con los valores del array en la diagonal

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

# **Reto**

---

Array tridimensional ordenado

In [77]:
cabeceras = [('nombre', 'S15'), ('edad', int), ('pais', 'S15')]
datos = [('Paco', 12, 'Colombia'), ('Maria', 54, 'Peru'), ('Monica', 23, 'Mexico')]
usuarios = np.array(datos, dtype=cabeceras)

np.sort(usuarios, order='edad')

array([(b'Paco', 12, b'Colombia'), (b'Monica', 23, b'Mexico'),
       (b'Maria', 54, b'Peru')],
      dtype=[('nombre', 'S15'), ('edad', '<i8'), ('pais', 'S15')])